--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/LunarMoon72/if-this-doesnt-work-i-hate-myself-2
build-by-default: true
branches:
- main
projects:
  if-this-doesnt-work-i-hate-myself-2:
    path: ""
...
